### PR TITLE
Extend meta data for .xsyg files and add spectrometer use

### PR DESCRIPTION
**Pull request by JohannesFriedrich**
An update to the *.xsyg file format. Now with:

- Usage of Spectrometer data
- Advanced meta data export

### CODE REVIEW

**Comment by wojdyr** [comment]
Hi Johannes, I cannot easily merge it, it shows me:

Conflicting files
xylib/xsyg.cpp

Could you rebase and update?

**Comment by JohannesFriedrich** [comment]
The problem should be solved now ...

**Comment by wojdyr** [comment]
Thanks!

**Comment by wojdyr** [comment]
I see that format uses different logic if detector == "Spectrometer". Do you happen to have an example file with detector="Spectrometer"?

**Comment by wojdyr** [comment]
I found TLSpectrum.xsyg which I used for testing, together with rfqm_uv.xsyg and XSYGExample.xsyg.
Then I refactored reading xsyg files.
It's mostly simplifications, whitespace changes, some typos in metadata (lexStuidoVersion, "<xmlattr>.simulator" -> stimulator).
The TLSpectrum.xsyg produced a file with a number of y columns, all with the same title "cts [1/ch]". I changed the title to a number from the XML file that precedes the y values. If it doesn't make sense please let me know. I'd like to release a new version of xylib soon.

**Comment by RLumSK** [comment]
Thank you! I double-checked and it looks good to me. The preceding y-values also make sense to me and the import test went well.

**Pull request merged**
