### PR TITLE
PAR-file support Bruker SPC + Example data

### PR DESCRIPTION
**Pull request by RLumSK**
* Add PAR-file support if available in the same folder als the SPC-file (relates to issue #13)
* Add example data for the XSYG-file format (own measurement data)

### CODE REVIEW

**Comment by wojdyr** [comment]
Hi Sebastian,
do you have example files?
I downloaded SPC and PAR files from https://github.com/tzerk/ESR/tree/master/inst/extdata
but when using xyconv to convert these files I get only one point, such as:

    1.000000	393.000000

**Comment by RLumSK** [comment]
@wojdyr You are right, there was something wrong. It was not the example file but a missing loop in the import function. This was introduced with commit ed3e677002e6331b100bb0a784cc74984a0f1840. I am sorry, I should have double-checked your changes, but obviously I did not do it (I was too impressed how concise they code became). 
Now all the lines are imported as they should be (see new pull request #21).

**Comment by wojdyr** [comment]
One more question about PAR files. In examples from tzerk/ESR the lines are separated with \r. I wonder - is it always \r or it depends on what systems these files are produced?
Perhaps you have your own examples of SPC/PAR files?

**Comment by RLumSK** [comment]
@wojdyr To my best knowledge, this is produced by the machine. However, I never worked myself with this magic machine @tzerk Perhaps you can comment on this? And perhaps you have even another example file we could add to the xy-library repository for testing purposes?

**Comment by tzerk** [comment]
For the particular example files in the ESR package note that the `.PAR` and `.SPC` files (important: capital letters! [this file](https://github.com/tzerk/ESR/blob/master/inst/extdata/mollusc.PAR)) were produced by a Bruker ESP300-E X-band-Spectrometer, which is controlled by an integrated PC running the `OS-9` operating system. As `OS-9` uses  `\r` (CR) as escape sequence for newlines and as to the best of my knowledge this particular device is not operable with another OS, we can surely assume that the lines in the `.PAR` files are always separated with `\r`.

As for the [other example `.par`](https://github.com/tzerk/ESR/blob/master/inst/extdata/DL_alanine.par), this was a data set provided by someone else who produced the data on an "older" generation, but unspecified Bruker EMXplus. I assume though, that this device was hooked up to a UNIX(-like) machine, thus the expected newline should probably be `LF` (`\n`).

**Comment by wojdyr** [comment]
@tzerk thanks for the comment. From what I see DL_alanine.par also has lines ended with \r. No idea about endiannes.
What's the best way to tell if the SPC file is of older or newer type?

**Comment by RLumSK** [comment]
I a private message @tzerk proposed to handle all, e.g., `\r, \r\n, \n`.

**Comment by wojdyr** [comment]
OK. I also refactored support for XSYG files, as noted at https://github.com/wojdyr/xylib/pull/16#issuecomment-689069880
If no problems are spotted I'll release a new version soon.

**Comment by RLumSK** [comment]
Looks so far all good to me and all the independent CI tests I run showed no problem. However, I got a compiler warning: 

> The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead"

Should we worry about it? Probably depending on the BH version, you used to build the software. For the moment, it is just the warning. However, the change dates back already to [2018](http://boost.2283326.n4.nabble.com/Deprecation-of-detail-endian-macros-td4704650.html).

**Comment by wojdyr** [comment]
Thanks for spotting it. I've addressed it now in 88c790025a6a4b9ea49db03f99dcb8cee0faf994

I'll try to make the long overdue release in the evening.

**Comment by RLumSK** [comment]
Thanks for this. I am currently running a couple of additional tests to make sure that this does not break on another platform. I  will get back with results in ca 30 min.

**Comment by RLumSK** [comment]
Ok, all checks went through. As soon as you have the new version released, I will also update the corresponding R package.

**Comment by wojdyr** [comment]
Thanks for the feedback. The new version is released.

**Pull request merged**
